// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAccount(arg1, arg2) {
  return window['go']['app']['App']['CreateAccount'](arg1, arg2);
}

export function GetAccounts() {
  return window['go']['app']['App']['GetAccounts']();
}

export function GetContracts(arg1) {
  return window['go']['app']['App']['GetContracts'](arg1);
}

export function GetFaction(arg1) {
  return window['go']['app']['App']['GetFaction'](arg1);
}

export function GetFactions() {
  return window['go']['app']['App']['GetFactions']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function ResetAllAccounts() {
  return window['go']['app']['App']['ResetAllAccounts']();
}
