// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {accounts} from '../models';
import {contracts} from '../models';
import {factions} from '../models';

export function CreateAccount(arg1:string,arg2:string):Promise<string>;

export function GetAccounts():Promise<Array<accounts.Account>>;

export function GetContracts(arg1:string):Promise<Array<contracts.Contract>>;

export function GetFaction(arg1:string):Promise<factions.Faction>;

export function GetFactions():Promise<Array<factions.Faction>>;

export function Greet(arg1:string):Promise<string>;

export function ResetAllAccounts():Promise<void>;
