// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateAccount(arg1:string,arg2:string):Promise<void>;

export function GetAccounts():Promise<Array<main.Account>>;

export function GetFactions():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function ResetAllAccounts():Promise<void>;
